apiVersion: v1
kind: Pod
metadata:
  labels:
    app: order
  name: order
spec:
  containers:
  - image: gcr.io/${PROJECT_ID}/${CLUSTERNAME}/microservice-order:1
    name: order
    ports:
    - containerPort: 8080