apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kubernetes-manifests/deployment-catalog.yaml

images:
- name: gcr.io/default-project/default-cluster/microservice-catalog
  newName: gcr.io/dein-projekt/dein-cluster/microservice-catalog # FILL YOUR DATA HERE
