apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kubernetes-manifests/catalog-deployment.yaml
- kubernetes-manifests/catalog-service.yaml

images:
- name: gcr.io/default-project/default-cluster/microservice-catalog
  newName: gcr.io/PROJEKT/CLUSTERNAME/microservice-catalog    # TRAGE DEINE DATEN HIER EIN
