apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kubernetes-manifests/customer-deployment.yaml
- kubernetes-manifests/customer-service.yaml

images:
- name: gcr.io/default-project/default-cluster/microservice-customer
  newName: gcr.io/PROJEKT/CLUSTERNAME/microservice-customer    # TRAGE DEINE DATEN HIER EIN
