apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kubernetes-manifests/customer-deployment.yaml

images:
- name: gcr.io/default-project/default-cluster/microservice-customer
  newName: gcr.io/dein-projekt/dein-cluster/microservice-customer # FILL YOUR DATA HERE
