apiVersion: v1
kind: Pod
metadata:
  labels:
    app: catalog
  name: catalog
spec:
  containers:
  - image: gcr.io/${PROJECT_ID}/${CLUSTERNAME}/microservice-catalog:1
    name: catalog
    ports:
    - containerPort: 8080