apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: catalog
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - image: gcr.io/default-project/default-cluster/microservice-catalog:1
        name: catalog
        ports:
        - containerPort: 8080
