apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kubernetes-manifests/deployment-apache.yaml

images:
- name: gcr.io/default-project/default-cluster/microservice-apache
  newName: gcr.io/dein-projekt/dein-cluster/microservice-apache # FILL YOUR DATA HERE
