apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kubernetes-manifests/apache-deployment.yaml
- kubernetes-manifests/apache-service.yaml

images:
- name: gcr.io/default-project/default-cluster/microservice-apache
  newName: gcr.io/PROJEKT/CLUSTERNAME/microservice-apache    # TRAGE DEINE DATEN HIER EIN
