apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: customer
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - image: gcr.io/default-projekt/default-cluster/microservice-customer:1
        name: customer
        ports:
        - containerPort: 8080
