# Default values for helm-chart.
# Declare variables to be passed into your templates.

replicaCount: 1
projectname: default-project
clustername: default-cluster
name: order
port: 8080
imageVersion: 1