apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kubernetes-manifests/order-deployment.yaml

images:
- name: gcr.io/default-projekt/default-cluster/microservice-order
  newName: gcr.io/dein-projekt/dein-cluster/microservice-order # TRAGE DEINE DATEN HIER EIN
