apiVersion: v1
kind: Pod
metadata:
  labels:
    run: apache
  name: apache
spec:
  containers:
  - image: gcr.io/${PROJECT_ID}/${CLUSTERNAME}/microservice-apache
    name: apache
    ports:
    - containerPort: 80