apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: apache
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: gcr.io/default-project/default-cluster/microservice-apache
        name: apache
        ports:
        - containerPort: 80