apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ quote .Values.name }}
  name: {{ quote .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ quote .Values.name }}
  template:
    metadata:
      labels:
        app: {{ quote .Values.name }}
    spec:
      containers:
      - name: {{ quote .Values.name }}
        image: gcr.io/{{ .Values.projectname }}/{{ .Values.clustername }}/microservice-{{ .Values.name }}:{{ .Values.imageVersion }}
        ports:
        - containerPort: {{ .Values.port }}
