apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: {{ quote .Values.name }}
    version: {{ quote .Values.deploymentVersion }}
  name: {{ quote .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: {{ quote .Values.name }}
  template:
    metadata:
      labels:
        run: {{ quote .Values.name }}
    spec:
      containers:
      - name: {{ quote .Values.name }}
        image: microservice-{{ .Values.name }}:{{ .Values.imageVersion }}
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.port }}
