apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ quote .Values.name }}
  name: {{ quote .Values.name }}
spec:
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    name: http    
  selector:
    run: {{ quote .Values.name }}
  type: LoadBalancer